# Generated by Django 4.2.20 on 2025-05-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_u4dioc.jpg', upload_to='profile_pics'),
        ),
    ]
