# Generated by Django 4.2.20 on 2025-05-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_u4dioc.jpg', upload_to='profile_pics'),
        ),
    ]
