# Generated by Django 4.2.20 on 2025-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='profile_pic',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
    ]
