# Generated by Django 4.2.20 on 2025-05-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='profile_pic',
            field=models.URLField(max_length=500),
        ),
    ]
